### ISSUE TITLE
sc2.protocol.ConnectionAlreadyClosed: Connection already closed.

### ISSUE THREAD

**Issue by AlexWanghaoming** [histmeisah/Large-Language-Models-play-StarCraftII#2]
I run test_the_env.py using the Linux version StarCraftII downloaded from https://github.com/Blizzard/s2client-proto#downloads, then an error raise: 

> Traceback (most recent call last):
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/site-packages/sc2/protocol.py", line 45, in __request
    response_bytes = await self._ws.receive_bytes()
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/site-packages/aiohttp/client_ws.py", line 281, in receive_bytes
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not bytes")
TypeError: Received message 257:None is not bytes
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/alpha/Large-Language-Models-play-StarCraftII/env/bot/Protoss_bot.py", line 2183, in protoss_agent_vs_build_in
    result = run_game(maps.get(map),
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/site-packages/sc2/main.py", line 496, in run_game
    result: Result = asyncio.run(_host_game(map_settings, players, **kwargs))
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/site-packages/sc2/main.py", line 369, in _host_game
    result = await _play_game(players[0], client, realtime, portconfig, game_time_limit, rgb_render_config)
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/site-packages/sc2/main.py", line 218, in _play_game
    player_id = await client.join_game(
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/site-packages/sc2/client.py", line 99, in join_game
    result = await self._execute(join_game=req)
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/site-packages/sc2/protocol.py", line 68, in _execute
    response = await self.__request(sc_pb.Request(**kwargs))
  File "/home/wanghm/anaconda3/envs/llm_smac/lib/python3.10/site-packages/sc2/protocol.py", line 51, in __request
    raise ConnectionAlreadyClosed("Connection already closed.") from exc
sc2.protocol.ConnectionAlreadyClosed: Connection already closed.

**Comment by histmeisah** [comment]
As i said in readme.md, Our experiments is test on windows 11 os, and BLZ didnt release the latest version of starcraft2 on linux os. So you should run our demo on windows os. There has so many balance update may impact our demo, so it is better for you tu run this demo on windows and use latest starcraft2. And if you find some error happen due to protobuf , you can reinstall burnysc2 again.
