### ISSUE TITLE
websocket timeout in sc2process.py

### ISSUE THREAD

**Issue by sli88389** [histmeisah/Large-Language-Models-play-StarCraftII#4]
i 've met this problem and tried to figure out whether it is Network problem or not , but seems to be others.....could you help me to solve  it?
action_dict {'TRAIN UNIT': {0: 'TRAIN PROBE', 1: 'TRAIN ZEALOT', 2: 'TRAIN ADEPT', 3: 'TRAIN STALKER', 4: 'TRAIN SENTRY', 5: 'TRAIN HIGHTEMPLAR', 6: 'TRAIN DARKTEMPLAR', 7: 'TRAIN VOIDRAY', 8: 'TRAIN CARRIER', 9: 'TRAIN TEMPEST', 10: 'TRAIN ORACLE', 11: 'TRAIN PHOENIX', 12: 'TRAIN MOTHERSHIP', 13: 'TRAIN OBSERVER', 14: 'TRAIN IMMORTAL', 15: 'TRAIN WARPPRISM', 16: 'TRAIN COLOSSUS', 17: 'TRAIN DISRUPTOR', 18: 'MORPH ARCHON'}, 'BUILD STRUCTURE': {19: 'BUILD PYLON', 20: 'BUILD ASSIMILATOR', 21: 'BUILD NEXUS', 22: 'BUILD GATEWAY', 23: 'BUILD CYBERNETICSCORE', 24: 'BUILD FORGE', 25: 'BUILD TWILIGHTCOUNCIL', 26: 'BUILD ROBOTICSFACILITY', 27: 'BUILD STARGATE', 28: 'BUILD TEMPLARARCHIVE', 29: 'BUILD DARKSHRINE', 30: 'BUILD ROBOTICSBAY', 31: 'BUILD FLEETBEACON', 32: 'BUILD PHOTONCANNON', 33: 'BUILD SHIELDBATTERY'}, 'RESEARCH TECHNIQUE': {34: 'RESEARCH WARPGATERESEARCH', 35: 'RESEARCH PROTOSSAIRWEAPONSLEVEL1', 36: 'RESEARCH PROTOSSAIRWEAPONSLEVEL2', 37: 'RESEARCH PROTOSSAIRWEAPONSLEVEL3', 38: 'RESEARCH PROTOSSAIRARMORSLEVEL1', 39: 'RESEARCH PROTOSSAIRARMORSLEVEL2', 40: 'RESEARCH PROTOSSAIRARMORSLEVEL3', 41: 'RESEARCH ADEPTPIERCINGATTACK', 42: 'RESEARCH BLINKTECH', 43: 'RESEARCH CHARGE', 44: 'RESEARCH PROTOSSGROUNDWEAPONSLEVEL1', 45: 'RESEARCH PROTOSSGROUNDWEAPONSLEVEL2', 46: 'RESEARCH PROTOSSGROUNDWEAPONSLEVEL3', 47: 'RESEARCH PROTOSSGROUNDARMORSLEVEL1', 48: 'RESEARCH PROTOSSGROUNDARMORSLEVEL2', 49: 'RESEARCH PROTOSSGROUNDARMORSLEVEL3', 50: 'RESEARCH PROTOSSSHIELDSLEVEL1', 51: 'RESEARCH PROTOSSSHIELDSLEVEL2', 52: 'RESEARCH PROTOSSSHIELDSLEVEL3', 53: 'RESEARCH EXTENDEDTHERMALLANCE', 54: 'RESEARCH GRAVITICDRIVE', 55: 'RESEARCH OBSERVERGRAVITICBOOSTER', 56: 'RESEARCH PSISTORMTECH', 57: 'RESEARCH VOIDRAYSPEEDUPGRADE', 58: 'RESEARCH PHOENIXRANGEUPGRADE', 59: 'RESEARCH TEMPESTGROUNDATTACKUPGRADE'}, 'OTHER ACTION': {60: 'SCOUTING PROBE', 61: 'SCOUTING OBSERVER', 62: 'SCOUTING ZEALOT', 63: 'SCOUTING PHOENIX', 64: 'MULTI-ATTACK', 65: 'MULTI-RETREAT', 66: 'CHRONOBOOST NEXUS', 67: 'CHRONOBOOST CYBERNETICSCORE', 68: 'CHRONOBOOST TWILIGHTCOUNCIL', 69: 'CHRONOBOOST STARGATE', 70: 'CHRONOBOOST FORGE', 71: 'EMPTY ACTION'}}
model_path_hf /home/lsj/llm/config/material/models/embedding/sentence-transformers_all-mpnet-base-v2
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
protoss_actions Collection created or retrieved.
vdb_path:  ../utils/actionvdb/action_vdb
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.3 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.9
wandb: Run data is saved locally in /home/lsj/llm/wandb/run-20240226_172133-ezow6uay
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run stellar-voice-3
wandb: ?? View project at https://wandb.ai/lsjjqh120/TextStarCraft2
wandb: ?? View run at https://wandb.ai/lsjjqh120/TextStarCraft2/runs/ezow6uay
2024-02-26 17:24:25.266 | INFO     | sc2.sc2process:_close_connection:231 - Closing connection at 36349...
2024-02-26 17:24:25.266 | INFO     | sc2.sc2process:_clean:242 - Cleaning up...
2024-02-26 17:24:25.267 | ERROR    | sc2.sc2process:_clean:257 - KILLED
2024-02-26 17:24:25.269 | INFO     | sc2.sc2process:_clean:274 - Cleanup complete
Process Process-3:
Traceback (most recent call last):
  File "/home/lsj/anaconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/lsj/anaconda3/envs/llm/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lsj/llm/env/bot/Protoss_bot.py", line 2183, in protoss_agent_vs_build_in
    result = run_game(maps.get(map),
  File "/home/lsj/anaconda3/envs/llm/lib/python3.10/site-packages/sc2/main.py", line 496, in run_game
    result: Result = asyncio.run(_host_game(map_settings, players, **kwargs))
  File "/home/lsj/anaconda3/envs/llm/lib/python3.10/site-packages/nest_asyncio.py", line 31, in run
    return loop.run_until_complete(task)
  File "/home/lsj/anaconda3/envs/llm/lib/python3.10/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/home/lsj/anaconda3/envs/llm/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/lsj/anaconda3/envs/llm/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/lsj/anaconda3/envs/llm/lib/python3.10/site-packages/sc2/main.py", line 357, in _host_game
    async with SC2Process(
  File "/home/lsj/anaconda3/envs/llm/lib/python3.10/site-packages/sc2/sc2process.py", line 108, in __aenter__
    self._ws = await self._connect()
  File "/home/lsj/anaconda3/envs/llm/lib/python3.10/site-packages/sc2/sc2process.py", line 228, in _connect
    raise TimeoutError("Websocket")
TimeoutError: Websocket

**Comment by histmeisah** [comment]
It seems like you run this repo on linux os right?
I have only test on Windows os, due to BLZ have not update the linux starcraft2.

**Comment by histmeisah** [comment]
And if you still have promblem, you can sent your contact information to my email address: [histmeisah@foxmail.com](mailto:histmeisah@foxmail.com)

**Comment by sli88389** [comment]
> It seems like you run this repo on linux os right? I have only test on Windows os, due to BLZ have not update the linux starcraft2.

that helps me a lot!!!! thaaaanks~

**Comment by histmeisah** [comment]
The problem has been solved
